- README.md
Pointing to opspec.io/opctl instead.
> Update README.md - opctl.io link is dead

- README.md
`https://opctl` can’t be reached.
> docs) change`https://opctl` to `https://opctl.io` [skip ci]

- cli/internal/core/runer.go
This allows graceful cleanup when piping opctl output into other commands.
Resolves https://github.com/opctl/opctl/issues/659
> Gracefully exit when SIGTERM is received

- sdks/go/model/scg.go
This fixes a bug if a opspec file is generated using `src` instead of `ref` for a container.
I found this when working on https://github.com/Remitly/infra-ops/tree/master/fpkg/run, looks like @psamaan may have manually patched this in vendored code 😬?
> Omit SCGContainerCallImage.Ref if empty

- .github/workflows/go.yml
- .travis.yml
- README.md
Travis open source is [end of life](https://docs.travis-ci.com/user/migrate/open-source-repository-migration/#frequently-asked-questions) and has severely throttled availability of executors, which makes builds really slow. This replaces travis builds with a github actions workflow
> Add a github workflow to replace travis

- sdks/go/node/core/containerruntime/docker/deleteContainerIfExists.go
- sdks/go/node/core/containerruntime/docker/deleteContainerIfExists_test.go
- sdks/go/node/core/containerruntime/docker/getContainerName.go
- sdks/go/node/core/containerruntime/docker/runContainer.go
#736 changed the name opctl assigns to docker containers, but it didn't update the teardown code, which can result in a docker container remaining alive after opctl stops tracking it. If ports are bound, this will cause the next op run to fail.
> Fix docker container removal

- .gitignore
Also, update the gitignore to prevent this. I've left the cli line in the gitignore in case people have old binaries hanging around.
> Delete accidentally committed binary

- .vscode/launch.json
- cli/cli.go
- cli/httpListener.go
- cli/node.go
- sdks/go/node/api/client/auths_adds.go
- sdks/go/node/api/client/liveness.go
- sdks/go/node/api/client/ops_kills.go
- sdks/go/node/api/client/ops_starts.go
- sdks/go/node/api/client/pkgs_ref_contents.go
- sdks/go/node/api/client/pkgs_ref_contents_path.go
- sdks/go/node/api/handler/ops/starts/handler.go
- sdks/go/node/core/addAuth.go
- sdks/go/node/core/addAuth_test.go
- sdks/go/node/core/callKiller_test.go
- sdks/go/node/core/caller.go
- sdks/go/node/core/containerCaller_test.go
- sdks/go/node/core/containerruntime/docker/containerRuntime.go
- sdks/go/node/core/containerruntime/docker/fsPathConverter.go
- sdks/go/node/core/containerruntime/docker/hostConfigFactory.go
- sdks/go/node/core/containerruntime/docker/hostruntime/runtimeinfo.go
- sdks/go/node/core/containerruntime/docker/runContainer.go
- sdks/go/node/core/containerruntime/k8s/containerRuntime.go
- sdks/go/node/core/core.go
- sdks/go/node/core/core_test.go
- sdks/go/node/core/startOp.go
- sdks/go/node/core/stateStore.go
- sdks/go/node/core/stateStore_test.go
- sdks/go/opspec/interpreter/call/interpret.go
- sdks/go/opspec/interpreter/call/interpret_test.go
- sdks/go/opspec/interpreter/call/op/interpret.go
This sets a better pattern for cleanup after op completion or error and should overall help with reliability.
There are now only three places where we create a "root" context (background only, no TODOs)
1. When initializing the CLI
2. When killing containers. This can be triggered when the root context is cancelled, so we don't want to use that previously cancelled context.
3. When the API handler starts an op. This is an asynchronous API, and the op keeps running after the initial start request finishes.
> Pass context throughout call paths where possible

- cli/cli.go
- cli/ui.go
Currently, the UI uses a hardcoded `localhost:42224`, instead of the provided cli argument listen address.
> Ensure UI uses the correct listen address

- cli/internal/nodeprovider/local/createNodeIfNotExists_test.go
- cli/internal/nodeprovider/local/killNodeIfExists_test.go
- cli/internal/nodeprovider/local/local_test.go
- sdks/go/data/coerce/toFile_test.go
- sdks/go/data/git/git_test.go
- sdks/go/data/git/pull_test.go
- sdks/go/node/core/caller_test.go
- sdks/go/node/core/core_test.go
- sdks/go/node/core/resolveData_test.go
- sdks/go/node/core/startOp_test.go
- sdks/go/opspec/install_test.go
- sdks/go/opspec/interpreter/call/container/dirs/interpret_test.go
- sdks/go/opspec/interpreter/call/container/interpret_test.go
- sdks/go/opspec/interpreter/call/interpret_test.go
- sdks/go/opspec/interpreter/dir/interpret_test.go
- sdks/go/opspec/interpreter/file/interpret_test.go
This makes one-off testing more reliable during local development. I've run into a few cases where running local tests, e.g. through vscode's debugger, fails due to leftover files from prior test runs.
> Use unique temporary directory in tests instead of global one

- CHANGELOG.md
- sdks/go/node/api/client/embedLocalFilesAndDirs.go
- sdks/go/node/api/client/embedLocalFilesAndDirs_test.go
- sdks/go/node/api/client/ops_starts.go
- sdks/go/node/api/client/ops_starts_test.go
- sdks/go/node/api/client/testdata/embedLocalFilesAndDirs/rootfile1.txt
- sdks/go/node/api/client/testdata/embedLocalFilesAndDirs/rootfile2.txt
- sdks/go/node/api/handler/handler.go
Today when I start an op on a remote node and I want to pass it a local file or directory as an arg, I have to write code to embed the files/dirs as objects. I would like whatever mechanism is needed to pass local files/dirs as args to an op to be performed automatically so I don't have to do it myself and so that as future enhancements like content defined chunking (CDC) and dedupe  are exposed via our data API, they will automatically be leveraged.
> Embed local file/dir values as objects when calling remote node

- .vscode/launch.json
- CHANGELOG.md
- CONTRIBUTING.md
- cli/events.go
- sdks/go/node/core/containerCaller.go
- sdks/go/node/core/opCaller.go
- sdks/go/node/core/parallelCaller.go
- sdks/go/opspec/interpreter/call/container/dirs/interpret.go
- sdks/go/opspec/interpreter/call/container/dirs/interpret_test.go
- sdks/go/opspec/interpreter/call/container/files/interpret.go
- sdks/go/opspec/interpreter/call/container/files/interpret_test.go
- sdks/go/opspec/interpreter/call/container/interpret_test.go
- sdks/go/opspec/interpreter/call/loop/iteration/scope.go
- sdks/go/opspec/interpreter/call/op/inputs/input/interpret.go
- sdks/go/opspec/interpreter/call/op/outputs/interpret.go
- sdks/go/opspec/interpreter/call/op/outputs/interpret_test.go
- sdks/go/opspec/interpreter/interpolater/interpolate.go
- sdks/go/opspec/interpreter/value/interpret.go
- sdks/go/opspec/ref.go
- sdks/go/opspec/ref_test.go
This introduces validation of outputs when making op calls. Currently, if an invalid output is used, it's ignored. When used later in an op, it's easy to misinterpret the errors produced as happening in the wrong place.
I made an attempt to try to detect common user-errors and proactively provide information to help solve the error (see test cases).
I also consolidated the scattered logic for converting a variable reference to its name (`$(foo)` to `foo`) into a single, unit tested, utility function.
This is technically backwards incompatible - currently if an invalid op output is specified and never used, it will be silently ignored. This changes so it will now cause an error, as it's not a valid reference. Resolving is as simple as removing the bad output line, so I think this is …
> Detect invalid outputs in opspecs

- CHANGELOG.md
I didn't notice this pattern until after merging https://github.com/opctl/opctl/pull/893
> Update format of links in changelog

- cli/ls.go
- cli/ls_test.go
Before:
```
REF	DESCRIPTION
fix	Attempts to fix source code linting issues.
lint	Lints source code, including formatting and in future static analysis.
Run the `fix` op to automatically fix what's fixable.
release	Releases forge by:  
1) compiling
2) uploading darwin/linux binaries to s3
3) creating a github release
test	runs unit tests
compile	turns source into runnable artifacts
```
After:
```
REF	DESCRIPTION
lint	Lints source code, including formatting and in future static analysis.
Run the `fix` op to automatically fix what's fixable.
release	Releases forge by:  
1) compiling
2) uploading darwin/linux binaries to s3
3) creating a github release
test	runs unit tests
compile	turns source into runnable artifacts
fix	Attempts to fix source code linting issues.
```
This could definitely be …
> Support multiline text in `opctl ls`

- CHANGELOG.md
- sdks/go/node/core/containerruntime/docker/imagePuller.go
- sdks/go/node/core/containerruntime/docker/imagePuller_test.go
- sdks/go/node/core/containerruntime/docker/internal/fakes/imagePuller.go
- sdks/go/node/core/containerruntime/docker/runContainer.go
- sdks/go/node/core/containerruntime/docker/runContainer_test.go
The goal here is to help avoid rate limiting errors we've been seeing frequently in CI builds, which are causing significant friction. Given CI nodes are swapped out regularly and we'll still always pull tagged or latest tagged images, this should be pretty resilient.
Resolves #920, INFRA-1870
> Skip pulling tagged, non-latest, already pulled images

- website/docusaurus.config.js
opctl no longer uses the master branch.  The edit links all point to the master branch.  They should instead point to main.
issue: https://github.com/opctl/opctl/issues/925
> change edit url from `master` to `main`

- sdks/go/opspec/interpreter/call/op/outputs/interpret.go
- sdks/go/opspec/interpreter/call/op/outputs/interpret_test.go
- sdks/go/opspec/opfile/unmarshal_test.go
In the [PR to error on invalid op output names](https://github.com/opctl/opctl/pull/893), we also removed support for the original output binding syntax. This syntax was never officially deprecated yet (I consider official here to be the CHANGELOG) and the syntax is for sure in use by consumers still. We should give at least a release worth of notice and probably much more since this syntax has been around for awhile. This adds it back for now and I added a [PR to deprecate it officially](https://github.com/opctl/opctl/pull/953).
> Add back support for deprecated output binding syntax

- CHANGELOG.md
- cli/cli.go
- cli/internal/clicolorer/cliColorer.go
- cli/internal/clicolorer/fakes/cliColorer.go
- cli/internal/clioutput/cliOutput.go
- cli/internal/clioutput/cliOutput_test.go
- cli/internal/clioutput/formatOpRef.go
- cli/internal/cliparamsatisfier/cliParamSatisfier.go
- cli/internal/cliparamsatisfier/cliParamSatisfier_test.go
- cli/internal/cliparamsatisfier/inputSrcFactory.go
- cli/internal/cliparamsatisfier/inputsrc/cliprompt/cliPrompt.go
- cli/internal/cliparamsatisfier/inputsrc/cliprompt/cliPrompt_test.go
- cli/internal/opgraph/callgraph.go
- cli/internal/opgraph/callgraph_test.go
- cli/internal/opgraph/formatting.go
- cli/internal/opgraph/formatting_test.go
- cli/internal/opgraph/loading.go
- cli/internal/opgraph/loading_test.go
- cli/internal/opgraph/outputmanager.go
- cli/internal/opgraph/outputmanager_test.go
- cli/run.go
- go.mod
When running an op via opctl run:
- display progress via a live call graph
- prefix log lines emitted by workloads with their op id & ref; closes #664
Note: this is basically a minimal port of the above features from @apexskier 's [branch](https://github.com/opctl/opctl/tree/mini-opctl). 
Just want to say a huge round of applause and thanks to @apexskier . This is some super cool & useful functionality.
> Live progress & log line prefixes from opctl run

- .github/workflows/go.yml
- website/docs/setup/azure-pipelines.md
- website/docs/setup/github.md
- website/docs/setup/travis.md
This also switches the main repo to use the documented github actions setup, which ensures it's using the most recent version of opctl and is less verbose.
> Fix github actions install link

- sdks/go/node/core/containerruntime/docker/deleteContainerIfExists.go
- sdks/go/node/core/containerruntime/docker/deleteContainerIfExists_test.go
- sdks/go/node/core/containerruntime/docker/runContainer.go
- sdks/go/node/core/containerruntime/docker/runContainer_test.go
This notifies containers with a SIGTERM signal, giving them a chance to gracefully shut down within a 3s timeout window. Containers that fail to stop within that window will be forced to terminate with a SIGKILL.
Note that the k8s runtime's pod deletion defaults to a graceful termination, so this change also brings the Docker runtime into alignment.
> Stop Docker containers gracefully before removing them

- website/docs/introduction.md
- website/docs/reference/cli/auth/index.md
- website/docs/reference/cli/node/index.md
- website/docs/reference/cli/op/index.md
- website/docs/training/containers/how-do-i-communicate-with-an-opctl-container.md
- website/docs/training/containers/how-do-i-get-opctl-containers-to-communicate.md
- website/docs/training/containers/how-do-i-run-a-container.md
- website/docusaurus.config.js
This PR changes the sidebar labels on the website CLI reference docs for nested CLI commands. Previously they were called "Overview" but this does not work as intended with latest version of Docusaurus which supports the concept of an index page; we therefore don't need an Overview page.
> Update CLI reference sidebar labels for CLI nested commands

- CHANGELOG.md
- cli/internal/clioutput/cliOutput.go
This PR updates the CLI event logging logic to include container errors, which should resolve #1032
> Fixes CLI no longer logs errors occurring in parallel calls; closes #1032

- .opspec/release/op.yml
- CHANGELOG.md
- sdks/go/node/containerruntime/k8s/k8s.go
This PR updates the k8s container runtime to explicitly delete terminated pods in order to avoid leaking terminated pods. Technically k8s does this automatically per [terminated-pod-gc-threshold](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-garbage-collection) but managed k8s such as EKS and GKE might not allow configuring this and the default is reported to be so high it could effect performance.
> Update K8s container runtime to explicitly delete terminated pods

- cli/internal/cliparamsatisfier/inputsrc/slice/slice.go
There's a crash that can be triggered when using an array input and forgetting to use the `name=` syntax on the CLI.
Before:
After:
> Fix crash on bad slice input parameter

- sdks/go/opspec/interpreter/call/interpret.go
- sdks/go/opspec/interpreter/call/interpret_test.go
Right now, it's often hard to distinguish between runs of a `parallelLoop`. You can add a name, but since there's a single `run` call it's the same name for each run. This makes a call's name interpreted as a string, which allows using variables (such as a variable for the parallel loop) as the name. (This also applies to `serialLoop`)
For this minimal example op the final graph is a lot more usable (I can tell what failed easier):
```yml
name: testloop
description: ""
inputs:
list:
array:
description: ""
run:
parallelLoop:
range: $(list)
vars:
value: $(value)
run:
name: validate-$(value)
container:
image: { ref: "apexskier/toolbox" }
envVars:
value:
cmd:
- bash
- -ce
- |
echo "$value" | grep a
```
Called with
```bash
opctl run -a list=["cat","dog","rabbit"] testloop
```
Output before: …
> Support variable references in call names

- .opspec/release/to-docker/dind.Dockerfile
- .opspec/release/to-docker/dood.Dockerfile
- .opspec/release/to-docker/op.yml
- cli/.opspec/compile/op.yml
This PR updates the release ops to publish the opctl/opctl docker hub images in both arm64 and amd64 architectures.
> Update release ops to publish arm64 arch images

- sdks/go/node/containerruntime/docker/isGpuSupported.go
- webapp/package.json
- webapp/src/components/CallHasOp/index.tsx
- yarn.lock
This PR is a small fix for the op visualization UI to properly handle variable op references. 
unrelated) it also fixes a warning from webpack in webapp about buffer dependency missing and optimizes the gpu support check on non-linux platforms.
> Properly handle variable op references in op visualization UI

- CHANGELOG.md
- opspec/opfile/jsonschema.json
- sdks/go/model/opSpec.go
- sdks/go/opspec/interpreter/call/container/cmd/interpret.go
- sdks/go/opspec/interpreter/call/container/cmd/interpret_test.go
- sdks/go/opspec/interpreter/call/container/interpret_test.go
- sdks/go/opspec/interpreter/call/op/inputs/interpret.go
- sdks/go/opspec/interpreter/call/op/params/param/array/validate.go
- sdks/go/opspec/interpreter/call/op/params/param/object/validate.go
- sdks/go/opspec/interpreter/call/op/params/validator.go
- test-suite/run/container/object/cmd/array/exit-zero/op.yml
- test-suite/run/container/object/cmd/array/exit-zero/scenarios.json
- test-suite/run/container/object/cmd/variable/array/exit-zero/op.yml
- test-suite/run/container/object/cmd/variable/array/exit-zero/scenarios.json
- website/docs/reference/opspec/op-directory/op/call/container/index.md
This PR allows using a variable to define `container.cmd`
It also fixes a bug where simultaneously defining a default plus constraints on an object or array input resulted in a validation error.
closes #1064
> Support variable reference as container.cmd

- .opspec/build/op.yml
When I tried to run the release op from main I ran into this error:
```
[59fe15fd] Status: Image is up to date for alpine:latest
[59fe15fd ./.opspec/build] fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/main/aarch64/APKINDEX.tar.gz
[59fe15fd ./.opspec/build] fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/community/aarch64/APKINDEX.tar.gz
[59fe15fd ./.opspec/build] v3.19.1-425-gc85850753c8 [https://dl-cdn.alpinelinux.org/alpine/v3.19/main]
[59fe15fd ./.opspec/build] v3.19.1-423-g66eaf3efa3e [https://dl-cdn.alpinelinux.org/alpine/v3.19/community]
[59fe15fd ./.opspec/build] OK: 22855 distinct packages available
[59fe15fd ./.opspec/build] (1/8) Installing ca-certificates (20240226-r0)
[59fe15fd ./.opspec/build] (2/8) Installing brotli-libs (1.1.0-r1)
[59fe15fd ./.opspec/build] (3/8) …
```
> download the correct architecture of codecov

- .github/workflows/build.yml
- .markdownlint/.markdownlint.json
- .markdownlint/customRule.js
- .opspec/check-for-changelog/check.sh
- .opspec/check-for-changelog/op.yml
- .opspec/lint/op.yml
- CHANGELOG.md
It would be cool to move opctl to CD. As a first step I'd like to introduce the following changes to CI/CD:
1. Add a job in CI that runs on PRs only. If the changelog is included in the diff, pass. If the changelog is not included then fail (but don't block CI) and print a warning message along the lines of ("WARNING: a new release will not be created when these changes are merged to main unless you add a new entry to CHANGELOG.md")
2. Add a job in CI that lints the current CHANGELOG to make sure it matches the keep-a-changelog format.
In a subsequent PR I'd like to add the following changes:
1. Add a job to the main branch's workflow that runs when CHANGELOG.md was edited. Parse the first version encountered in the file and run the release op using that as the new version. The release …
> Check whether Changelog is included in diff, lint changelog on main and in PR

- .github/workflows/build.yml
- .opspec/build/op.yml
- .opspec/release/to-github/op.yml
- .opspec/test/op.yml
- cli/.opspec/compile/op.yml
Prior to this change, when someone runs the `compile` op in the CLI directory, their binary will be built with a version `0.0.1`. That's not desirable because new maintainers can very easily miss that they're expected to provide a new version when they compile the opctl CLI 😅. This change:
1. removes all default values for `version` inputs in ops
2. removes `version` as an input from the test op because that appears to have been introduced as a copy pasta (it's not used in the op at all)
3. Updates the `github.release.create` op to version 2.0.0 from 1.2.0
1. I expect CI to continue to pass
2. Locally I ran the `compile` op in the CLI directory and verified that the built binary has a version that I expect.
> do not set default version in ops

- .github/workflows/build.yml
- .markdownlint/customRule.js
- .opspec/release/check.sh
- .opspec/release/op.yml
- .opspec/release/to-github/op.yml
- CHANGELOG.md
Create a release on merge to main if CHANGELOG was updated to add a new version
I ran the release op from my laptop and you can see that a new release was created and new containers were pushed to ghcr
> Create a release whenever changes are merged to main that include an updated CHANGELOG

- CHANGELOG.md
- cli/internal/opgraph/callgraph.go
- sdks/go/data/fs/fs.go
- sdks/go/data/git/clone.go
- sdks/go/data/git/parseRef.go
- sdks/go/data/resolve.go
- sdks/go/model/errors.go
- sdks/go/node/api/handler/data/ref/handler.go
Type `opctl run aisdjufbhiaudbh` in a repo and observe it take a very long time to figure out that the op doesn’t exist.
opctl takes ~1.5 mins to resolve ops that do not exist. It takes this long because `httpClient` is using https://github.com/sethgrid/pester that will retry on certain error codes. The node's `/api/data/{ref}` endpoint returns 500 error if we don't detect the error. This makes it so that it retries ~90 times before it fails.
- Use additional custom errors to detect common errors when attempting to resolve ops through node's `/api/data/{ref}` endpoint
- Return http status error codes that match the result when trying to resolve node's api/data so that retry doesn't occur
- More consistent error formatting
> Fix long time to resolve if op does not exist

- cli/nodeCreate.go
- sdks/go/node/api/listen.go
- sdks/go/node/core.go
- sdks/go/node/core_test.go
- sdks/go/node/datadir/datadir.go
- sdks/go/opspec/interpreter/call/container/interpret.go
- sdks/go/opspec/interpreter/reference/direntry/interpret.go
- sdks/go/opspec/interpreter/reference/interpret.go
This PR fixes an edge case encountered in testing on OSX following #1112 where variables were initialized by mounting to container files/dirs would error with `invalid mount config [...] permission denied`.
Upon investigation it was found that:
On Docker for Mac, the file sync between VM and host doesn't have access to `root` (UID=0) owned files unless the owning group also has access. 
Additionally, by default umask is `022` so this was leading to no owning group write access and the error scenario.
> Ensure permissions on opctl data can't be broken by umask

- .opspec/release/op.yml
Need to pass HOME to the getLatestRelease op since it requires it. Wasn't caught in testing pre-merge because the only way to test is to run a release (which happens post merge) ; ).
> Fix release op

- .opspec/changelog/getLatestRelease/main.go
Casing of changelog/getLatestRelease ops latestRelease.isPrerelease was not matching what was expected.
As with prior PR, this wasn't caught in testing pre-merge because the only way to test is to run a release (which happens post merge) ; ).
> Fix changelog/getLatestRelease op output casing

- .opspec/changelog/getLatestRelease/go.mod
- .opspec/changelog/getLatestRelease/go.sum
- .opspec/changelog/getLatestRelease/main.go
- CHANGELOG.md
- cli/internal/nodeprovider/local/createNodeIfNotExists.go
- sdks/go/node/dns/internal/resolvercfg/apply_linux.go
This PR addresses two last touchups before release 0.1.56 namely:
- not requiring explicitly using sudo to start a node if the caller has passwordless sudo enabled
- address a regression for the linux os where container dns names wouldn't work
> Release prep; Fix container dns names on linux & support passwordless sudo for node startup

- .github/workflows/build.yml
- .markdownlint/customRule.js
- CHANGELOG.md
- cli/internal/opgraph/callgraph.go
- sdks/go/internal/unsudo/createFile.go
- sdks/go/node/containerruntime/docker/isGpuSupported.go
- sdks/go/node/dns/internal/resolvercfg/delete_darwin.go
- website/docs/reference/opspec/op-directory/op/call/container/index.md
- website/docs/training/containers/container-networking.md
This PR is a fast follow to address several issues reported after releasing  0.1.56, namely:
- Fix 'opctl node kill' before you've ever run an op'
- Fix: Rate limit errors surfacing as "image not found" errors
- Don't log "not found in graph" to logs (noisy without value)
- Fixed file initialization results in incorrect (empty) file data
> Fast follow to address issues reported in 0.1.56

- .github/workflows/build.yml
- .opspec/release/op.yml
- .opspec/release/to-github/op.yml
This is PR fixes an issue where if our change log release notes included JSON special characters such as double quotes, it would break the release process. This was because the `github.com/opspec-pkgs/github.release.create` op was not properly encoding them. This issue has been resolved in the latest version of that op so updating to it will resolve it. 
Unrelated:
We also updated to latest version of `github.com/opspec-pkgs/github.release.upload` in order to only need to pass `accessToken` instead of username & accessToken
> Fix release notes with JSON special characters break release

- CHANGELOG.md
- sdks/go/node/containerruntime/docker/runContainer.go
This is a short term band-aid for issue #1137. Rather than failing out entirely when GPU passthrough errors out, we simply function like GPU passthrough isn't possible.
> Allow Failure In GPU Support Check To Just Mean GPU Passthrough Is Not Supported

- CHANGELOG.md
- cli/selfUpdate.go
This PR leverages the recently introduced native privilege escalation handling for self-update which saves people from having to "sudo self-update".
> Leverage native privilege escalation handling for self-update

- CHANGELOG.md
- cli/cli.go
Converts the short-form arguments and options to long-form to allow for `EnvVar` on each CLI option.
> Add environment variables support for each option and argument

- CHANGELOG.md
- sdks/go/node/containerruntime/docker/runContainer.go
This PR fixes a bug where container name registrations were not being cleaned up on container exit. This led to name registrations becoming invalid as the previously assigned IPs were assigned to new containers with different names.
> Fix accessing containers by name from opctl nodes stops working due to prior registrations not being cleaned up on container exit

- CHANGELOG.md
- opspec/opfile/jsonschema.json
- sdks/go/model/call.go
- sdks/go/model/opSpec.go
- sdks/go/node/containerruntime/docker/pullImage.go
- sdks/go/opspec/interpreter/call/container/image/interpret.go
- sdks/go/opspec/interpreter/call/container/image/interpret_test.go
- sdks/go/opspec/interpreter/call/container/image/platform/interpret.go
- sdks/go/opspec/interpreter/call/container/image/platform/interpret_test.go
- sdks/go/opspec/interpreter/call/container/image/platform/pkg.go
- sdks/go/opspec/interpreter/call/container/image/platform/suite_test.go
- website/docs/reference/opspec/op-directory/op/call/container/image.md
- website/docs/reference/opspec/op-directory/op/call/oci-image-platform.md
This PR adds the ability to specify image platform architecture (e.g. `amd64`) in order to ensure containers requiring images built for a particular architecture don't break when run on nodes with different architecture.
example op using it:
```yaml
name: examplePlatformUsage
run:
container:
image:
ref: amd64/python:3.12
platform:
arch: amd64
```
Unrelated:
This PR also removes container.image.src attribute in the opspec JSON schema; it is [not used/supported in code](https://github.com/opctl/opctl/blob/155cc1f46837790c9da3be8c7b1f346ca07d503a/sdks/go/model/opSpec.go#L46)
closes #1156
> Support specifying image.platform.arch in container calls

- CHANGELOG.md
- sdks/go/internal/unsudo/newCmd.go
- sdks/go/node/containerruntime/embedded/embedded.go
- sdks/go/node/containerruntime/embedded/ensureLimaBinaries.go
This PR includes a small update to remove a hardcoded UID and GID from the embedded container runtime (which may not exist on a given system), in favor of using the callers UID & GID, (which is guaranteed to exist on a given system).
> Update embedded container runtime to run as caller UID & GID
